### ISSUE TITLE
X99Z V102A, X99Z V104, X99-K9

### ISSUE THREAD

**Issue by eugene159** [BIOS-iEngineer/MACHINIST-X99ZV102#11]
Thank you for your BIOS, works great!
Besides the original X99Z V102 there are three new version available on the market:
X99Z V102A
X99Z V104
X99-K9

Can you take a look why TDP monitoring in AIDA64 and HWMonitor shows incorrect figures for those new versions ? (significantly less than it should be)

**Comment by BIOS-iEngineer** [comment]
Errors in PCB design.

**Comment by eugene159** [comment]
> So you think it's a hardware issue and not possible to fix with bios mod ?

**Comment by PalaGergo** [comment]
Just I'd like to ask to please confirm that 
IF my x99v102a mobo EEPROM is Winbond 25Q128JVSQ  which is a 128 bit EEPROM it means 16MB BIOS is fit to that (128kbits=16MB) - even my actual is 8MB - t if I'm right (or NOT?) so safe to flash even warning messages that layout bla bla is different?
Thanx a lot

**Comment by BIOS-iEngineer** [comment]
8Mb is only the BIOS area, 16Mb is a complete BIOS, it would be best for you to study the information about the BIOS through google search and buy a programmer device before modifying something yourself
