### ISSUE TITLE
This bios is support X99Z V104 motherboard?

### ISSUE THREAD

**Issue by thestreetdj** [BIOS-iEngineer/MACHINIST-X99ZV102#12]
This version of the bios
Do you also support the latest main board?

**Comment by BIOS-iEngineer** [comment]
People who tested said this BIOS works in V104 (Intel C612)

**Comment by PalaGergo** [comment]
I'd like to ask is there any chance that you could provide a 8MB version for X99Z V102A as C:\AfuWin64>AFUWINx64.EXE old_rom_x99z_v102a.rom /O   output is   8 388 608 old_rom_x99z_v102a.rom big for me and yours are 16MB.
I'm looking for BIOS bugfix, removal of useless menu and adding useful menues like able to set XMP profile for my RAMs.. I'm happy to do myself if it's not convient for you just need some guidance ... I could provide my actual BIOS ...

Thanx a lot

**Comment by BIOS-iEngineer** [comment]
I don't make BIOS on request between times
