### ISSUE TITLE
Gbe.region?

### ISSUE THREAD

**Issue by charcharwon** [BIOS-iEngineer/MACHINIST-X99ZV102#3]
Trying to use xpenology but only works with original bios, but need video card in system to post and bricks system changing some bios settings. Lots of solder and desolder to reflash.

With this bios xpenology not seen on network, but can boot without video card, I flashed and bricked a lot trying to figure out and editing, is it because it is missing Gbe region?
Thank you

**Comment by BIOS-iEngineer** [comment]
before asking a question, find out what the Gbe region is and how it applies to this board
