### ISSUE TITLE
ECC disabled

### ISSUE THREAD

**Issue by ifsnop** [BIOS-iEngineer/MACHINIST-X99ZV102#4]
Hi! I have this board, and with the shipped BIOS, ECC memory modules can be used, but ECC is disabled.

Linux at boot says:

kernel: EDAC sbridge: CPU SrcID #0, Ha #0, Channel #0 has DIMMs, but ECC is disabled
kernel: EDAC sbridge: Couldn't find mci handler
kernel: EDAC sbridge: Failed to register device with error -19.

Memtest86+ also states that ECC is disabled, this is the easiest way to test, without booting Linux.

Do you think that with your BIOS, board will be able to use ECC? Thanks!

**Comment by BIOS-iEngineer** [comment]
China doesn't follow standards. Try it

**Comment by ifsnop** [comment]
Do I need to desolder the chip? Or is there any other way to load BIOS? Never upgraded BIOS on a China mb.

**Comment by ifsnop** [comment]
Your BIOS solved the problem. Original bios (6 feb 2020) didn't have ECC Enabled, your version enabled ECC and memtest & linux are detecting and using it. Many thanks!

**Comment by BIOS-iEngineer** [comment]
> Your BIOS solved the problem. Original bios (6 feb 2020) didn't have ECC Enabled, your version enabled ECC and memtest & linux are detecting and using it. Many thanks!

✔ good for you

**Comment by karakondjo** [comment]
ifsnop, which BIOS do you use?
Dear BISO-iEngineer, pls, help with this ECC-problem.

**Comment by BIOS-iEngineer** [comment]
Hallo! For use ECC module you need install a version 23 firmware.

**Comment by karakondjo** [comment]
Thanks for the answer!
The problem is that my BIOS is 8 MB (the Machinist mobo is v102a ).
Here I attached both my original and modded (with the excellent miyconst's method):
[ORIGINAL_X99Z_v102a_BIOS.zip](https://github.com/BIOS-iEngineer/MACHINIST-X99ZV102/files/6050669/ORIGINAL_X99Z_v102a_BIOS.zip)
[Final_undervolted_X99z.zip](https://github.com/BIOS-iEngineer/MACHINIST-X99ZV102/files/6050671/Final_undervolted_X99z.zip)

**Comment by BIOS-iEngineer** [comment]
Do you have a programer device? You can download the full 16MB bios 23 versions and make any modification, but if you do not have a programmer and you do not know the difference 8Mb from 16Mb, it is better you do not start experimenting.

**Comment by karakondjo** [comment]
No.. I use AfuWin

**Comment by BIOS-iEngineer** [comment]
I bought in one Chinese store EZP2019 and it has been working properly for 4 years., See product and seller reviews. EZP2019 universal programmer.

**Comment by ifsnop** [comment]
No, it's not. Your bios is 16MB.

> Thanks for the answer!
> The problem is that my BIOS is 8 MB (the Machinist mobo is v102a ).
> Here I attached both my original and modded (with the excellent miyconst's
> method):
> ORIGINAL_X99Z_v102a_BIOS.zip
> <https://github.com/BIOS-iEngineer/MACHINIST-X99ZV102/files/6050669/ORIGINAL_X99Z_v102a_BIOS.zip>
> Final_undervolted_X99z.zip
> <https://github.com/BIOS-iEngineer/MACHINIST-X99ZV102/files/6050671/Final_undervolted_X99z.zip>
>
