### ISSUE TITLE
CSM can't be disabled, sSATA settings has disappeared (is used in M.2)

### ISSUE THREAD

**Issue by JanCernyCZ** [BIOS-iEngineer/MACHINIST-X99ZV102#7]
Hello, I purchased this board for low-cost build.

Config:

- Xeon E5-2620 v3
- Machinist X99Z v102 from [this seller](https://www.aliexpress.com/item/4000995326329.html), original BIOS 2020-06-02 AAX99018
- 2× 16 GB reg. ECC DDR4-2133 @1866 2Rx4
- Quadro K2000 2 GB
- WD Blue 3D M.2 SATA 500 GB
- Lite-On iHAS120 X DVD±RW
- Seasonic SS-400ET F3 80PLUS Bronze
- Windows 10 Pro 2004
- latest drivers (INF, RSTe, MEI) from win-raid forum
![Lenovo-case](https://user-images.githubusercontent.com/40010595/94368734-1a616280-00e6-11eb-982a-becdb55a8b63.jpg)

Your BIOS looks better than the original, however, there are some problems:

1. CSM can't be disabled, there is no UEFI/legacy priority options. I tested multiple graphics cards with an integrated EFI GOP module (GeForce 210, Radeon HD8570, Quadro K2200). Always with same result. UEFI boot on GPT partition is working smoothly. I can confirm working Sleep & Hibernation mode.
![CSM](https://user-images.githubusercontent.com/40010595/94368268-67900500-00e3-11eb-9d09-87b25aa300a0.jpg)
2. sSATA settings has disappeared (1 of 4 sSATA port is used in M.2 slot).
3. SATA numbers in Setup don't match physical numbering on the motherboard.
![SATA](https://user-images.githubusercontent.com/40010595/94368127-ec2e5380-00e2-11eb-9011-126e55f03af8.jpg)
4. Boot time in task manager is not calculated correctly. Enable & disable Fast Boot has no effect. I think this is MEI version issue. ![boot](https://user-images.githubusercontent.com/40010595/94368002-2a774300-00e2-11eb-98a6-1ce6b1ee3ac8.png)

**Comment by BIOS-iEngineer** [comment]
1) CSM module is disabled only if the video card supports UEFI
2) SATA numbering is wrong marked on the board
3) sSATA works in SSD mode
4) Other architecture errors
![CSM](https://user-images.githubusercontent.com/69295506/94374282-cec5ad80-0113-11eb-81b4-e415fd5d3cad.png)

**Comment by JanCernyCZ** [comment]
With the original motherboard BIOS is EFI GOP detected correctly and CSM can be disabled.

Here is details from my cards:
**GeForce 210**
`Dumping info from = GT218-Samsung_updGOP.rom

NVIDIA Firmware Update Utility (Version 5.531.0)
Copyright (C) 1993-2018, NVIDIA Corporation. All rights reserved.

Sign-On Message       : NVIDIA GeForce 210 VGA BIOS
MSINV809MS.580
Build GUID            : Blank
IFR Subsystem ID      : Blank
Subsystem Vendor ID   : 0x1462
Subsystem ID          : 0x8094
Version               : 70.18.49.00.00
Image Hash            : N/A
Product Name          : GT218 Board - 08730000
Device Name(s)        : GeForce 210
Board ID              : 0xC86A
Vendor ID             : 0x10DE
Device ID             : 0x0A65
Hierarchy ID          : Normal Board
Chip SKU              : 300
Project               : 0873-0000
Build Date            : 12/01/09
Modification Date     : 09/16/14
UEFI Version          : 0x10031
UEFI Variant ID       : 0x0000000000000001 ( GT21x )
UEFI Signer(s)        : Microsoft Corporation UEFI CA 2011
XUSB-FW Version ID    : N/A
XUSB-FW Build Time    : N/A
InfoROM Version       : N/A
InfoROM Backup        : Not Present
License Placeholder   : Not Present
GPU Mode              : N/A
`
**Radeon HD 8570**
`Dumping info from = Oland.rom

Image 1 -- Offset 0x0
=======================
  ROM header contents:
    Signature              0xAA55
    PCIR offset            0x0224
  PCI Data Structure
    Signature              PCIR
    Vendor ID              0x1002
    Device ID              0x6611
    PCI Revision           0x00
    Image size             0x10000
    Code revision          0x0F1B
    Indicator              0x00   (Not last image)
    Code type              0x00   (PCAT Image)
  Legacy BIOS File Name    C5520200.101
  Legacy BIOS Part Number  113-C5520200-101
  Legacy BIOS Build Number 245039
  Legacy BIOS Change List  838302
  Binary BIOS_IDTF         0x54942882
  ByteCheckSum             0
Image 2 -- Offset 0x10000
=======================
  ROM header contents:
    Signature              0xAA55
    PCIR offset            0x001C
  PCI Data Structure
    Signature              PCIR
    Vendor ID              0x1002
    Device ID              0x6611
    PCI Revision           0x00
    Image size             0xF600
    Code revision          0x0000
    Indicator              0x80   (last image)
    Code type              0x03   (EFI Image)
    EFI Signature          0x0EF1
    Compression Type       0x0001 (compressed)
    Machine type           0x8664 (X64)
    Subsystem              0x000B (EFI boot service driver)
    EFI image offset       0x006C (abs: 0x1006C)
  Uefi Ids from EFI_PCI_EXPANSION_ROM_HEADER:
    UefiSourceRevision
    UefiSourceChangeList
    UefiBiosBuildNumber

  Dump Gop Driver Info:
    Machine type code      X64
    The GOP Driver appears to be Authenticode signed.
    Size Of Gop Image      102944 (100 KB)
    GOP Driver Name: AMD GOP X64 Driver Rev.1.41.0.15.27.LibBuildNo:2077.Oct 24
2012.20:33:56
    GOP AMD_Build          245039
    GOP AMD_CL             838302
    GOP BIOS_IDTF          0x54942882
    GOP Driver contains tables
    Legacy BIOS_IDTF       0x54942882
`
**Quadro K2200 4 GB**
`Dumping info from = GM107-K2200-Hynix.rom


NVIDIA Firmware Update Utility (Version 5.531.0)
Copyright (C) 1993-2018, NVIDIA Corporation. All rights reserved.


Sign-On Message       : GM107 P2010 SKU 0500 VGA BIOS (HWDIAG)
Build GUID            : Blank
IFR Subsystem ID      : 103C-1097
Subsystem Vendor ID   : 0x103C
Subsystem ID          : 0x1097
Version               : 82.07.A4.00.0C
Image Hash            : 8BD8C0BBA0487760B505272C499BDAB8
Product Name          : GM107 Board - 20100500
Device Name(s)        : Quadro K2200
Board ID              : 0xE711
Vendor ID             : 0x10DE
Device ID             : 0x13BA
Hierarchy ID          : Normal Board
Chip SKU              : 875-0
Project               : 2010-0500
Build Date            : 04/14/16
Modification Date     : 06/22/16
UEFI Version          : 0x10036
UEFI Variant ID       : 0x0000000000000005 ( GM1xx )
UEFI Signer(s)        : Microsoft Corporation UEFI CA 2011
XUSB-FW Version ID    : N/A
XUSB-FW Build Time    : N/A
InfoROM Version       : 2010.0500.00.03
InfoROM Backup        : Not Present
License Placeholder   : Not Present
GPU Mode              : N/A
`

**Comment by BIOS-iEngineer** [comment]
minimum graphics card with UEFI GTX 1050 for test - works correctly. minimum graphics card with legacy ATI HD4500 for test - works correctly.
the message says that your video is running as legacy, not UEFI

**Comment by JanCernyCZ** [comment]
Just tried reference Sapphire RX 470 4 GB Platinum edition with the same result.

**Comment by BIOS-iEngineer** [comment]
Permanently UEFI
[C612RD23R-Permanently-UEFI.zip](https://github.com/BIOS-iEngineer/MACHINIST-X99ZV102/files/5289124/C612RD23R-Permanently-UEFI.zip)

**Comment by JanCernyCZ** [comment]
Flashed with programmer, F9 for Load Optimized defaults. CSM Support seems Disabled.

Thank you. It was help!

**Comment by BIOS-iEngineer** [comment]
😊✔
