### ISSUE TITLE
Missing PCI-E Bifurcation options

### ISSUE THREAD

**Issue by miyconst** [BIOS-iEngineer/MACHINIST-X99ZV102#8]
Hi @BIOS-iEngineer.

I am currently testing this BIOS with an [ALZENIT X99-PE7](https://www.aliexpress.com/item/4001157528899.html), it works really well, but for some reason you hid the IIO settings which contains PCI-E Bifurcation options.

I have enabled the settings and tested with an [Asus Hyper M.2 X16 V2](https://www.asus.com/Motherboard-Accessories/HYPER-M-2-X16-CARD-V2/) card. 

These options are probably not that useful for X99Z, since it has only one PCI-E x16 slot, but I am still curious to know why you have decided to hide it. Are there any issues with it?

**Comment by BIOS-iEngineer** [comment]
may damage the board if the settings are incorrect

**Comment by miyconst** [comment]
Could you please elaborate? Which settings are "incorrect" and how it may damage the board?

**Comment by BIOS-iEngineer** [comment]
these settings contain control functions PCIe

**Comment by miyconst** [comment]
![image](https://user-images.githubusercontent.com/6435556/94995732-90f7d780-05a0-11eb-804c-e2eabebcac22.png)

Here are the settings I had to manually apply in order to get mine [Asus Hyper M.2 X16 V2](https://www.asus.com/Motherboard-Accessories/HYPER-M-2-X16-CARD-V2/) card work.

**Comment by BIOS-iEngineer** [comment]
Good, I reconfigure after

**Comment by BIOS-iEngineer** [comment]
Fixed in next release
