### ISSUE TITLE
Restore A/C On Power Loss does not work

### ISSUE THREAD

**Issue by miyconst** [BIOS-iEngineer/MACHINIST-X99ZV102#9]
The `Restore A/C On Power Loss` option does not work with [ALZENIT X99-PE7](https://www.aliexpress.com/item/4001157528899.html).

I am not sure if it's an issue of the BIOS or the motherboard, but the value is never saved and it always stays as `Power Off` even if I pick and save `Power On`.

P.S. I will test this function with a Machinist X99Z if possible.

**Comment by BIOS-iEngineer** [comment]
I doubt that this board is being made as a server. I never tested this function.

**Comment by miyconst** [comment]
>I doubt that this board is being made as a server. I never tested this function.

This function is often needed in other scenarios than server. It would be nice to get it working if possible.

**Comment by BIOS-iEngineer** [comment]
I'll check after

**Comment by ifsnop** [comment]
On the machinist board, the setting is reset from power on to power off if you shutdown your motherboard during post when using your bios. With default bios this doesn't happen, and setting is preserved.

It will be really good to have this setting fixed.

**Comment by BIOS-iEngineer** [comment]
No way to activate, the reason: hardware errors in the board architecture

**Comment by ifsnop** [comment]
Hi, default bios manages restore a/c on power loss ok (but has other
problems). Maybe it can be ported to your bios build?

> No way to activate, the reason: hardware errors in the board architecture
>

**Comment by BIOS-iEngineer** [comment]
you can experience, after completing the testing update 24 version I start another project.

**Comment by miyconst** [comment]
>you can experience, after completing the testing update 24 version I start another project.

@BIOS-iEngineer I don't quite get what you mean, but as far as I remember, `Restore On AC/Power loss` function works with the original Machinist BIOS, but I can't validate it right now since I don't have the board.

**Comment by BIOS-iEngineer** [comment]
with the original BIOS a lot that the rest does not work, and this setting keeps working for 1 minute, then after minute nothing happens. 🤪 use for servers another board.

**Comment by miyconst** [comment]
>with the original BIOS a lot that the rest does not work, and this setting keeps working for 1 minute, then after minute nothing happens. 🤪 use for servers another board.

I see. I will test a bit more when I get mine X99Z-K9.
